name: Flutter GitHub Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Access Workflow
        uses: actions/checkout@v2.3.2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.3.2

      - name: Get Packages
        run: flutter pub get

      # - name: Run Unit Test
      #   run: flutter test

      - name: Build AppBundle
        run: flutter build appbundle --obfuscate --split-debug-info=build/split_debug_info
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks

      - name: Get AppBundle
        uses: actions/upload-artifact@v2
        with:
          name: aab-ascii-generator
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Get ARM64 Obfuscate Symbols
        uses: actions/upload-artifact@v2
        with:
          name: obfuscate-ascii-generator-arm64
          path: build/split_debug_info/app.android-arm64.symbols

      - name: Get ARM Obfuscate Symbols
        uses: actions/upload-artifact@v2
        with:
          name: obfuscate-ascii-generator-arm
          path: build/split_debug_info/app.android-arm.symbols

      - name: Get X86 Obfuscate Symbols
        uses: actions/upload-artifact@v2
        with:
          name: obfuscate-ascii-generator-x86
          path: build/split_debug_info/app.android-x64.symbols